import { Theme, makeStyles } from '@material-ui/core/styles'

export const useStyles = makeStyles((theme: Theme) => ({
  root: {
    position: 'relative',
    padding: '24px 16px',
    background: '#fff',
    minHeight: 640,
    backgroundImage:
      'radial-gradient(at 50% 25%,rgba(219,121,17,0.04) 40%,transparent 60%)',
    '@media (max-width:768px)': {
      padding: '24px 32px',
    },
  },
  head: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  content: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  wide: {
    width: '100%',
    '@media (min-width:768px)': {
      width: '75%',
      paddingRight: 32,
    },
  },
  h1: {
    fontWeight: 400,
    marginBottom: 16,
    fontSize: 28,
    color: '#40558b',
  },
  h2: {
    fontSize: 14,
    color: '#8492ce',
  },
  h3: {
    color: '#48558b',
    fontSize: 16,
  },
  h4: {
    fontWeight: 400,
    fontSize: 24,
    color: '#48558b',
    marginBottom: 24,
  },
  h5: {
    marginBottom: 12,
    fontSize: 16,
    color: '#48558b',
    paddingTop: 4,
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
    overflow: 'hidden',
  },
  h6: {
    fontSize: 14,
    color: '#8492ce',
    paddingTop: '5px 8px',
    height: 26,
    background: '#f2eeea',
    width: 'fit-content',
    padding: '0px 4px',
  },
  h7: {
    fontWeight: 400,
    fontSize: 24,
    color: '#48558b',
  },
  h8: {
    color: '#666',
    marginLeft: 36,
  },
  moreBtn: {
    height: 45,
    cursor: 'pointer',
    '@media (max-width: 768px)': {
      marginLeft: 16,
    },
  },
  icon4: {
    width: 18,
    marginRight: 10,
  },
  btn1: {
    fontSize: 16,
    alignItems: 'center',
    textAlign: 'left',
    padding: 16,
    border: 'none',
    color: '#666',
    justifyContent: 'normal',
    textTransform: 'capitalize',
  },
  btnDiv: {
    // borderRadius: 16,
    overflow: 'hidden',
    background: '#fff',
    boxShadow: '0 0 24px rgb(0 0 0 / 10%)',
    display: 'grid',
    backgroundImage:
      'radial-gradient(at 50% 25%,rgba(219, 121, 17, 0.04) 40%,transparent 60%)',
  },
  eventItem: {
    padding: 16,
    borderRadius: 16,
    background: '#f8f4f0',
    display: 'flex',
  },
  avatar: {
    borderRadius: '50%',
    height: 64,
    width: 64,
    marginRight: 16,
  },
  clockIcon: { width: 15, verticalAlign: 'bottom' },
  stateDiv: {
    display: 'flex',
    justifyContent: 'flex-start',
    margin: -8,
    flexWrap: 'wrap',
  },
  onlineDiv: {
    padding: 16,
    margin: 8,
    borderRadius: 16,
    display: 'flex',
    background: '#f8f5f3',
    width: '35%',
  },
  icon1: {
    width: 50,
    height: 50,
    marginLeft: -8,
    marginTop: -8,
  },
  leaderboard: {
    background: 'rgba(0,0,0,.025)',
    padding: '0px 16px',
    borderRadius: 16,
  },
  leadItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid rgba(0,0,0,.04)',
    padding: '20px 0px',
    '&:first-child': {
      borderBottom: '1px solid rgba(0,0,0,.04)',
    },
  },
  icon2: {
    width: 15,
    height: 15,
    marginLeft: 6,
    cursor: 'pointer',
    color: '#48558b',
  },
  icon3: {
    borderColor:
      'rgba(214, 219, 78, 0.5) rgba(237, 244, 22, 0.7) rgba(199, 206, 4, 0.6) rgba(84, 12, 153, 0.4)',
    width: 1,
    height: 1,
    marginLeft: 12,
    marginRight: 12,
    transform: 'rotate(45deg)',
    borderStyle: 'solid',
    background: '#fff',
    borderRadius: 1,
    borderWidth: '7px 5px 5px 7px',
  },
  div1: {
    alignItems: 'center',
    display: 'flex',
  },
  keyboardModal: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  keyboardPaper: {
    backgroundColor: '#fffdfc',
    width: '100%',
    height: '100%',
  },
  keyboardHeader: {
    justifyContent: 'space-between',
    display: 'flex',
    padding: '32px 24px',
    position: 'relative',
    maxWidth: 540,
    width: '100%',
    margin: 'auto',
    alignItems: 'center',
  },
  icon5: {
    color: 'rgba(0,0,0,.6)',
    cursor: 'pointer',
  },
  keyboardContent: {
    width: '100%',
    height: '90%',
    display: 'flex',
    alignItems: 'center',
    overflowY: 'scroll',
    flex: '1 1',
  },
  keyboardControls: {
    padding: '0px 24px 24px 24px',
    maxWidth: 540,
    margin: 'auto',
    width: '100%',
  },
  keyboardItems: {
    marginTop: 32,
    alignItems: 'center',
    display: 'flex',
  },
  keyboardItems1: {
    borderTop: '1px solid #eee',
    marginTop: 32,
    // justifyContent: 'space-between',
    alignItems: 'center',
    display: 'flex',
    padding: '32px 0px',
  },
  keyboardItems2: {
    borderTop: '1px solid #eee',
    // justifyContent: 'space-between',
    alignItems: 'center',
    display: 'flex',
    padding: '32px 0px',
  },
  canvasDiv: {
    display: 'flex',
  },
  iconBtn2: {
    background: '#fff',
    border: '1px solid rgba(0,0,0,.06)',
    boxShadow: '0 2px 8px rgb(0 0 0 / 8%)',
    borderRadius: 3,
    width: '30px',
    fontWeight: 500,
    cursor: 'pointer',
  },
  div2: {
    display: 'grid',
    height: 100,
    padding: 10,
    marginTop: 'auto',
    marginBottom: 100,
  },
  keyboard: {
    width: 100,
    display: 'flex',
    justifyContent: 'space-between',
  },
  key: {
    width: 30,
    background: '#eee',
    borderRadius: 3,
    // boxShadow:
    //   '0 1px 1px rgb(0 0 0 / 10%), inset 0 2px 0 0 hsl(0deg 0% 100% / 70%)',
    color: '#333',
    textAlign: 'center',
    padding: '1px 0px 1px',
    whiteSpace: 'nowrap',
    fontSize: 12,
    border: '1px solid #b3b1b1de',
  },
  key1: {
    width: 30,
    padding: '1px 0px 1px',
  },
}))
